$schema: https://json-schema.org/draft-07/schema
$defs:
  Accounts:
    additionalProperties: false
    description: InNoHassle Accounts integration settings
    properties:
      api_url:
        default: https://api.innohassle.ru/accounts/v0
        description: API URL for InNoHassle Accounts
        title: Api Url
        type: string
      api_jwt_token:
        description: JWT token for accessing the Accounts API as a service
        format: password
        title: Api Jwt Token
        type: string
        writeOnly: true
    required:
    - api_jwt_token
    title: Accounts
    type: object
  Authentication:
    additionalProperties: false
    properties:
      allowed_domains:
        default:
        - localhost
        - 127.0.0.1
        - 0.0.0.0
        description: Allowed domains for redirecting after authentication
        items:
          type: string
        title: Allowed Domains
        type: array
      jwt_private_key:
        description: Private key for JWT. Use 'openssl genrsa -out private.pem 2048'
          to generate keys
        format: password
        title: Jwt Private Key
        type: string
        writeOnly: true
      jwt_public_key:
        description: Public key for JWT. Use 'openssl rsa -in private.pem -pubout
          -out public.pem' to generate keys
        title: Jwt Public Key
        type: string
      session_secret_key:
        description: Secret key for sessions. Use 'openssl rand -hex 32' to generate
          keys
        format: password
        title: Session Secret Key
        type: string
        writeOnly: true
    required:
    - jwt_private_key
    - jwt_public_key
    - session_secret_key
    title: Authentication
    type: object
  Environment:
    enum:
    - development
    - production
    - testing
    title: Environment
    type: string
  InnopolisSSO:
    additionalProperties: false
    description: Innopolis SSO settings (only for production)
    properties:
      client_id:
        description: Client ID for Innopolis SSO
        title: Client Id
        type: string
      client_secret:
        description: Client secret for Innopolis SSO
        format: password
        title: Client Secret
        type: string
        writeOnly: true
      redirect_uri:
        description: Redirect URI for Innopolis SSO
        title: Redirect Uri
        type: string
      resource_id:
        anyOf:
        - type: string
        - type: 'null'
        default: null
        description: Resource ID for Innopolis SSO (optional); Used for Sports API
          access
        title: Resource Id
    required:
    - client_id
    - client_secret
    - redirect_uri
    title: InnopolisSSO
    type: object
  Mongo:
    additionalProperties: false
    properties:
      uri:
        description: MongoDB database connection URI
        format: password
        title: Uri
        type: string
        writeOnly: true
    required:
    - uri
    title: Mongo
    type: object
  SMTP:
    additionalProperties: false
    properties:
      host:
        description: SMTP server host
        title: Host
        type: string
      port:
        default: 587
        description: SMTP server port
        title: Port
        type: integer
      username:
        description: SMTP server username
        title: Username
        type: string
      password:
        description: SMTP server password
        format: password
        title: Password
        type: string
        writeOnly: true
    required:
    - host
    - username
    - password
    title: SMTP
    type: object
  Telegram:
    additionalProperties: false
    properties:
      bot_username:
        description: Bot username for Telegram
        title: Bot Username
        type: string
      bot_token:
        description: Bot token for Telegram
        format: password
        title: Bot Token
        type: string
        writeOnly: true
    required:
    - bot_username
    - bot_token
    title: Telegram
    type: object
additionalProperties: false
description: Settings for the application. Get settings from `settings.yaml` file.
properties:
  app_root_path:
    default: ''
    description: Prefix for the API path (e.g. '/api/v0')
    title: App Root Path
    type: string
  environment:
    $ref: '#/$defs/Environment'
    default: development
    description: App environment
  mongo:
    $ref: '#/$defs/Mongo'
    description: MongoDB settings
  web_url:
    description: Web URL for the frontend part of InNoHassle-Accounts
    title: Web Url
    type: string
  cors_allow_origins:
    default:
    - https://innohassle.ru
    - https://pre.innohassle.ru
    - http://localhost:3000
    description: 'Allowed origins for CORS: from which domains requests to the API
      are allowed'
    items:
      type: string
    title: Cors Allow Origins
    type: array
  auth:
    $ref: '#/$defs/Authentication'
    description: Authentication settings
  innopolis_sso:
    anyOf:
    - $ref: '#/$defs/InnopolisSSO'
    - type: 'null'
    default: null
    description: Innopolis SSO settings (only for production)
  telegram:
    anyOf:
    - $ref: '#/$defs/Telegram'
    - type: 'null'
    default: null
    description: Telegram settings
  accounts:
    anyOf:
    - $ref: '#/$defs/Accounts'
    - type: 'null'
    default: null
    description: Use production InNoHassle Accounts API for authentication in local
      development
  smtp:
    anyOf:
    - $ref: '#/$defs/SMTP'
    - type: 'null'
    default: null
    description: SMTP settings
  $schema:
    description: Path to the schema file
    title: Schema
    type: string
required:
- mongo
- web_url
- auth
title: Settings
type: object
