name: Run pre-commit

on: [ push, pull_request ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ‘¾ Check out repository
        uses: actions/checkout@v4
      - name: ðŸ“¦ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: ðŸ“¦ Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          activate-environment: true
      - name: ðŸ“¦ Install the project
        run: uv sync
      - name: ðŸ§ª Run pre-commit
        run: uv run pre-commit run --show-diff-on-failure --color=always --all-files --hook-stage manual
        env:
          RUFF_FORMAT: github
